import type { CompanyIndustry } from './industry';

export const LOOKUP_SEED = {
  department: [
    'Operations',
    'Customer Service',
    'Shipping & Print',
    'Sales',
    'Management',
    'Administration',
    'Fulfillment',
    'Front Desk',
    'Service',
    'Kitchen',
    'Production',
    'Field Operations',
    'Clinical',
  ],
  job_title: [
    'Print & Shipping Associate',
    'Customer Service Associate',
    'Retail Sales Associate',
    'Shift Supervisor',
    'Assistant Manager',
    'Store Manager',
    'Notary Associate',
    'Nail Technician',
    'Server',
    'Cook',
    'Roofing Laborer',
    'Production Worker',
    'Medical Assistant',
    'Front Desk Receptionist',
  ],
  employment_type: [
    'Full-Time',
    'Part-Time',
    'Seasonal',
    'Contract',
    'Temporary',
    'Either',
  ],
  salary_range: [
    '$12 – $14/hr',
    '$14 – $16/hr',
    '$16 – $18/hr',
    '$18 – $22/hr',
    '$22 – $28/hr',
    '$28 – $35/hr',
    '$35,000 – $45,000/year',
    '$45,000 – $55,000/year',
    '$55,000 – $70,000/year',
    'Competitive — DOE',
  ],
  location: [
    'On-site',
    'In-store',
    'Store Location',
    'Hybrid',
  ],
  requirement: [
    'Friendly and professional attitude',
    'Reliable and punctual',
    'Basic computer skills',
    'Customer service experience preferred',
    'Must be authorized to work in the United States',
    'Ability to stand for extended periods',
    'Ability to lift up to 50 lbs',
    'Cash handling experience',
    'POS system experience',
    'Shipping and packing experience',
    'Strong communication skills',
    'Team-oriented mindset',
    'Flexible schedule including weekends',
    'High school diploma or equivalent',
    'Leadership or supervisory experience',
    'State license or certification (or willing to obtain)',
    'Food handler certification (or willing to obtain)',
    'Valid driver\'s license',
    'OSHA safety training preferred',
  ],
  benefit: [
    'Flexible scheduling',
    'Team-oriented environment',
    'Growth and advancement opportunities',
    'Employee discounts',
    'Paid training',
    'Competitive pay',
    'Health insurance (full-time)',
    'Paid time off',
    '401(k) retirement plan',
    'Holiday pay',
    'Performance bonuses',
    'Career development programs',
    'Supportive management',
    'Stable work environment',
    'Cross-training opportunities',
    'Tips (where applicable)',
  ],
} as const;

export type LookupCategory = keyof typeof LOOKUP_SEED;

export interface SystemTemplateSeed {
  title: string;
  department: string;
  employmentType: string;
  salaryRange: string;
  locationType: string;
  description: string;
  requirements: string[];
  benefits: string[];
}

function tpl(
  title: string,
  department: string,
  employmentType: string,
  salaryRange: string,
  locationType: string,
  description: string,
  requirements: string[],
  benefits: string[],
): SystemTemplateSeed {
  return { title, department, employmentType, salaryRange, locationType, description, requirements, benefits };
}

const COMMON_REQ = [
  'Must be authorized to work in the United States',
  'Reliable and punctual',
  'Friendly and professional attitude',
];

const COMMON_BEN = [
  'Competitive pay',
  'Paid training',
  'Team-oriented environment',
  'Growth and advancement opportunities',
];

export const SYSTEM_TEMPLATES_BY_INDUSTRY: Record<
  Exclude<CompanyIndustry, 'CUSTOM'>,
  SystemTemplateSeed[]
> = {
  SHIPPING_RETAIL: [
    tpl(
      'Print & Shipping Associate',
      'Shipping & Print',
      'Full-Time',
      '$16 – $18/hr',
      'On-site',
      'Greet customers, process shipping and packing orders, handle printing and document services, and operate the POS system while maintaining a clean store environment.',
      [...COMMON_REQ, 'Basic computer skills', 'Customer service experience preferred', 'Ability to lift up to 50 lbs', 'Shipping and packing experience'],
      [...COMMON_BEN, 'Flexible scheduling'],
    ),
    tpl(
      'Customer Service Associate',
      'Customer Service',
      'Part-Time',
      '$14 – $16/hr',
      'On-site',
      'Assist customers with inquiries, process transactions, and ensure every visitor has a positive in-store experience.',
      [...COMMON_REQ, 'Basic computer skills', 'Strong communication skills', 'Cash handling experience'],
      [...COMMON_BEN, 'Flexible scheduling', 'Employee discounts'],
    ),
    tpl(
      'Notary Associate',
      'Operations',
      'Part-Time',
      '$16 – $18/hr',
      'In-store',
      'Provide notary services while supporting general store operations including customer service, shipping, and printing.',
      [...COMMON_REQ, 'Notary commission (or willing to obtain)', 'Customer service experience preferred', 'Strong communication skills'],
      [...COMMON_BEN, 'Flexible scheduling'],
    ),
    tpl(
      'Store Manager',
      'Management',
      'Full-Time',
      '$55,000 – $70,000/year',
      'On-site',
      'Lead full store operations including P&L performance, hiring, training, customer experience, and compliance.',
      [...COMMON_REQ, 'Leadership or supervisory experience', 'Retail or franchise experience preferred', 'Inventory management experience', 'High school diploma or equivalent'],
      [...COMMON_BEN, 'Health insurance (full-time)', 'Paid time off', '401(k) retirement plan', 'Performance bonuses'],
    ),
    tpl(
      'Shift Supervisor',
      'Management',
      'Full-Time',
      '$18 – $22/hr',
      'On-site',
      'Lead store operations during assigned shifts, coach associates, and ensure service standards are met.',
      [...COMMON_REQ, 'Leadership or supervisory experience', 'Customer service experience preferred', 'Flexible schedule including weekends'],
      [...COMMON_BEN, 'Performance bonuses', 'Career development programs'],
    ),
  ],
  NAIL_SALON: [
    tpl(
      'Nail Technician',
      'Service',
      'Full-Time',
      '$16 – $22/hr',
      'On-site',
      'Perform manicures, pedicures, gel applications, and nail art services while maintaining sanitation standards and building client relationships.',
      [...COMMON_REQ, 'State nail technician license (or willing to obtain)', 'Customer service experience preferred', 'Ability to stand for extended periods'],
      [...COMMON_BEN, 'Tips (where applicable)', 'Flexible scheduling', 'Employee discounts'],
    ),
    tpl(
      'Pedicure Technician',
      'Service',
      'Part-Time',
      '$14 – $18/hr',
      'On-site',
      'Specialize in pedicure services including foot care, exfoliation, massage, and polish application in a relaxing salon environment.',
      [...COMMON_REQ, 'State nail technician license (or willing to obtain)', 'Customer service experience preferred'],
      [...COMMON_BEN, 'Tips (where applicable)', 'Flexible scheduling'],
    ),
    tpl(
      'Receptionist',
      'Front Desk',
      'Part-Time',
      '$14 – $16/hr',
      'On-site',
      'Greet clients, schedule appointments, manage the front desk, process payments, and keep the reception area welcoming.',
      [...COMMON_REQ, 'Basic computer skills', 'Strong communication skills', 'Cash handling experience'],
      [...COMMON_BEN, 'Flexible scheduling', 'Employee discounts'],
    ),
    tpl(
      'Salon Manager',
      'Management',
      'Full-Time',
      '$45,000 – $55,000/year',
      'On-site',
      'Oversee daily salon operations, staff scheduling, inventory, client satisfaction, and business performance.',
      [...COMMON_REQ, 'Leadership or supervisory experience', 'Salon or spa management experience preferred', 'Strong communication skills'],
      [...COMMON_BEN, 'Health insurance (full-time)', 'Performance bonuses', 'Career development programs'],
    ),
    tpl(
      'Lash Technician',
      'Service',
      'Full-Time',
      '$18 – $28/hr',
      'On-site',
      'Apply lash extensions, perform lash lifts, and consult with clients on aftercare and maintenance.',
      [...COMMON_REQ, 'Lash certification (or willing to obtain)', 'Attention to detail', 'Customer service experience preferred'],
      [...COMMON_BEN, 'Tips (where applicable)', 'Paid training', 'Flexible scheduling'],
    ),
    tpl(
      'Waxing Specialist',
      'Service',
      'Part-Time',
      '$16 – $22/hr',
      'On-site',
      'Perform waxing services for face and body, maintain hygiene protocols, and educate clients on post-treatment care.',
      [...COMMON_REQ, 'Waxing certification preferred', 'Customer service experience preferred', 'Professional bedside manner'],
      [...COMMON_BEN, 'Tips (where applicable)', 'Flexible scheduling', 'Employee discounts'],
    ),
  ],
  RESTAURANT: [
    tpl(
      'Server',
      'Front of House',
      'Part-Time',
      '$14 – $16/hr + tips',
      'On-site',
      'Take orders, serve food and beverages, and provide attentive hospitality to ensure an excellent dining experience.',
      [...COMMON_REQ, 'Customer service experience preferred', 'Flexible schedule including weekends', 'Ability to stand for extended periods'],
      [...COMMON_BEN, 'Tips (where applicable)', 'Flexible scheduling', 'Meal discounts'],
    ),
    tpl(
      'Cook',
      'Kitchen',
      'Full-Time',
      '$16 – $20/hr',
      'On-site',
      'Prepare menu items to spec, maintain kitchen cleanliness, follow food safety standards, and support line efficiency during service.',
      [...COMMON_REQ, 'Food handler certification (or willing to obtain)', 'Kitchen experience preferred', 'Ability to work in a fast-paced environment'],
      [...COMMON_BEN, 'Paid training', 'Meal discounts', 'Flexible scheduling'],
    ),
    tpl(
      'Dishwasher',
      'Kitchen',
      'Part-Time',
      '$12 – $14/hr',
      'On-site',
      'Wash dishes, utensils, and kitchen equipment; keep the dish area organized and support back-of-house operations.',
      [...COMMON_REQ, 'Ability to stand for extended periods', 'Reliable and punctual'],
      [...COMMON_BEN, 'Flexible scheduling', 'Meal discounts'],
    ),
    tpl(
      'Host',
      'Front of House',
      'Part-Time',
      '$12 – $14/hr',
      'On-site',
      'Greet guests, manage waitlists and reservations, and coordinate seating to keep the dining room running smoothly.',
      [...COMMON_REQ, 'Strong communication skills', 'Friendly and professional attitude', 'Flexible schedule including weekends'],
      [...COMMON_BEN, 'Flexible scheduling', 'Meal discounts'],
    ),
    tpl(
      'Manager',
      'Management',
      'Full-Time',
      '$45,000 – $55,000/year',
      'On-site',
      'Lead restaurant operations including staffing, inventory, customer service standards, and daily financial performance.',
      [...COMMON_REQ, 'Leadership or supervisory experience', 'Restaurant management experience preferred', 'Food handler certification (or willing to obtain)'],
      [...COMMON_BEN, 'Health insurance (full-time)', 'Paid time off', 'Performance bonuses'],
    ),
  ],
  ROOFING: [
    tpl(
      'Roofing Laborer',
      'Field Operations',
      'Full-Time',
      '$16 – $22/hr',
      'On-site',
      'Assist with tear-off, installation, and cleanup on residential and commercial roofing projects under crew lead direction.',
      [...COMMON_REQ, 'Ability to lift up to 50 lbs', 'Comfort working at heights', 'Valid driver\'s license', 'OSHA safety training preferred'],
      [...COMMON_BEN, 'Paid training', 'Overtime opportunities', 'Stable work environment'],
    ),
    tpl(
      'Sales Representative',
      'Sales',
      'Full-Time',
      'Competitive — DOE',
      'Hybrid',
      'Conduct in-home inspections, prepare estimates, and close roofing contracts while representing the company professionally.',
      [...COMMON_REQ, 'Valid driver\'s license', 'Strong communication skills', 'Sales experience preferred'],
      [...COMMON_BEN, 'Performance bonuses', 'Company vehicle or mileage reimbursement', 'Career development programs'],
    ),
    tpl(
      'Project Manager',
      'Management',
      'Full-Time',
      '$55,000 – $70,000/year',
      'Hybrid',
      'Coordinate roofing projects from estimate through completion, manage crews, schedules, materials, and customer communication.',
      [...COMMON_REQ, 'Leadership or supervisory experience', 'Construction or roofing experience preferred', 'Valid driver\'s license'],
      [...COMMON_BEN, 'Health insurance (full-time)', 'Paid time off', 'Performance bonuses'],
    ),
    tpl(
      'Estimator',
      'Sales',
      'Full-Time',
      '$45,000 – $55,000/year',
      'Hybrid',
      'Inspect properties, measure roofs, prepare detailed estimates, and support the sales team with accurate proposals.',
      [...COMMON_REQ, 'Roofing or construction estimating experience preferred', 'Valid driver\'s license', 'Strong communication skills'],
      [...COMMON_BEN, 'Performance bonuses', 'Paid training', 'Career development programs'],
    ),
    tpl(
      'Office Assistant',
      'Administration',
      'Part-Time',
      '$14 – $16/hr',
      'On-site',
      'Support office operations including scheduling, invoicing, customer follow-ups, and general administrative tasks.',
      [...COMMON_REQ, 'Basic computer skills', 'Strong communication skills', 'Organizational skills'],
      [...COMMON_BEN, 'Flexible scheduling', 'Stable work environment'],
    ),
  ],
  FACTORY: [
    tpl(
      'Production Worker',
      'Production',
      'Full-Time',
      '$16 – $18/hr',
      'On-site',
      'Operate production equipment, meet daily output targets, and follow safety and quality procedures on the manufacturing floor.',
      [...COMMON_REQ, 'Ability to stand for extended periods', 'Ability to lift up to 50 lbs', 'OSHA safety training preferred'],
      [...COMMON_BEN, 'Overtime opportunities', 'Health insurance (full-time)', 'Paid training'],
    ),
    tpl(
      'Assembly Technician',
      'Production',
      'Full-Time',
      '$16 – $20/hr',
      'On-site',
      'Assemble components to specification, perform in-process quality checks, and document production output.',
      [...COMMON_REQ, 'Manufacturing or assembly experience preferred', 'Attention to detail', 'Ability to lift up to 50 lbs'],
      [...COMMON_BEN, 'Paid training', 'Cross-training opportunities', 'Stable work environment'],
    ),
    tpl(
      'QA/QC Inspector',
      'Production',
      'Full-Time',
      '$18 – $22/hr',
      'On-site',
      'Inspect finished goods, document defects, and ensure products meet quality standards before shipment.',
      [...COMMON_REQ, 'Quality control experience preferred', 'Attention to detail', 'Basic computer skills'],
      [...COMMON_BEN, 'Health insurance (full-time)', 'Career development programs'],
    ),
    tpl(
      'Shipping & Receiving',
      'Fulfillment',
      'Full-Time',
      '$16 – $18/hr',
      'On-site',
      'Receive inbound materials, pick and pack orders, and prepare outbound shipments with accurate documentation.',
      [...COMMON_REQ, 'Forklift certification preferred', 'Ability to lift up to 50 lbs', 'Inventory management experience'],
      [...COMMON_BEN, 'Overtime opportunities', 'Paid training'],
    ),
    tpl(
      'Supervisor',
      'Management',
      'Full-Time',
      '$22 – $28/hr',
      'On-site',
      'Supervise production teams, enforce safety protocols, track KPIs, and coordinate shift schedules.',
      [...COMMON_REQ, 'Leadership or supervisory experience', 'Manufacturing experience preferred', 'OSHA safety training preferred'],
      [...COMMON_BEN, 'Health insurance (full-time)', 'Performance bonuses', '401(k) retirement plan'],
    ),
  ],
  RETAIL: [
    tpl(
      'Retail Sales Associate',
      'Sales',
      'Part-Time',
      '$14 – $16/hr',
      'In-store',
      'Assist customers on the sales floor, maintain product displays, and support daily store operations.',
      [...COMMON_REQ, 'Customer service experience preferred', 'Flexible schedule including weekends', 'Cash handling experience'],
      [...COMMON_BEN, 'Employee discounts', 'Flexible scheduling'],
    ),
    tpl(
      'Cashier',
      'Sales',
      'Part-Time',
      '$12 – $14/hr',
      'In-store',
      'Process customer transactions accurately, handle returns, and provide friendly checkout service.',
      [...COMMON_REQ, 'Cash handling experience', 'POS system experience', 'Friendly and professional attitude'],
      [...COMMON_BEN, 'Flexible scheduling', 'Employee discounts'],
    ),
    tpl(
      'Stock Associate',
      'Operations',
      'Part-Time',
      '$14 – $16/hr',
      'On-site',
      'Receive and unpack inventory, restock shelves, and maintain organized backroom and sales floor areas.',
      [...COMMON_REQ, 'Ability to lift up to 50 lbs', 'Ability to stand for extended periods'],
      [...COMMON_BEN, 'Flexible scheduling', 'Employee discounts'],
    ),
    tpl(
      'Assistant Manager',
      'Management',
      'Full-Time',
      '$35,000 – $45,000/year',
      'On-site',
      'Support the store manager with staffing, training, inventory, and customer service standards.',
      [...COMMON_REQ, 'Leadership or supervisory experience', 'Retail experience preferred', 'Strong communication skills'],
      [...COMMON_BEN, 'Health insurance (full-time)', 'Performance bonuses', 'Career development programs'],
    ),
    tpl(
      'Store Manager',
      'Management',
      'Full-Time',
      '$45,000 – $55,000/year',
      'On-site',
      'Lead all store operations including sales goals, hiring, merchandising, and customer experience.',
      [...COMMON_REQ, 'Leadership or supervisory experience', 'Retail management experience preferred', 'Inventory management experience'],
      [...COMMON_BEN, 'Health insurance (full-time)', 'Paid time off', '401(k) retirement plan'],
    ),
  ],
  MEDICAL_OFFICE: [
    tpl(
      'Front Desk Receptionist',
      'Front Desk',
      'Full-Time',
      '$14 – $18/hr',
      'On-site',
      'Greet patients, schedule appointments, verify insurance, and manage front office workflow.',
      [...COMMON_REQ, 'Basic computer skills', 'Strong communication skills', 'Customer service experience preferred', 'HIPAA awareness preferred'],
      [...COMMON_BEN, 'Health insurance (full-time)', 'Paid time off', 'Stable work environment'],
    ),
    tpl(
      'Medical Assistant',
      'Clinical',
      'Full-Time',
      '$16 – $22/hr',
      'On-site',
      'Room patients, take vitals, assist providers with procedures, and maintain clinical supplies and records.',
      [...COMMON_REQ, 'Medical assistant certification (or willing to obtain)', 'HIPAA awareness preferred', 'Professional bedside manner'],
      [...COMMON_BEN, 'Health insurance (full-time)', 'Paid training', 'Career development programs'],
    ),
    tpl(
      'Billing Specialist',
      'Administration',
      'Full-Time',
      '$16 – $20/hr',
      'On-site',
      'Process insurance claims, follow up on denials, post payments, and support patient billing inquiries.',
      [...COMMON_REQ, 'Medical billing experience preferred', 'Basic computer skills', 'Attention to detail'],
      [...COMMON_BEN, 'Health insurance (full-time)', 'Paid time off'],
    ),
    tpl(
      'Office Manager',
      'Management',
      'Full-Time',
      '$45,000 – $55,000/year',
      'On-site',
      'Oversee office operations, staff scheduling, compliance, vendor relationships, and patient experience.',
      [...COMMON_REQ, 'Healthcare office management experience preferred', 'Leadership or supervisory experience', 'Strong communication skills'],
      [...COMMON_BEN, 'Health insurance (full-time)', 'Paid time off', '401(k) retirement plan'],
    ),
  ],
};

/** @deprecated use SYSTEM_TEMPLATES_BY_INDUSTRY */
export const JOB_TEMPLATES_SEED = SYSTEM_TEMPLATES_BY_INDUSTRY.SHIPPING_RETAIL;
