import type { CompanyIndustry } from './industry';

export type { LookupSeedData } from './job-lookup-seed';
export {
  LOOKUPS_BY_INDUSTRY,
  LOOKUP_SEED,
  getLookupSeedForIndustry,
  getAllSeededLookupValues,
} from './job-lookup-seed';

export interface SystemTemplateSeed {
  title: string;
  department: string;
  employmentType: string;
  salaryRange: string;
  locationType: string;
  description: string;
  requirements: string[];
  benefits: string[];
}

function tpl(
  title: string,
  department: string,
  employmentType: string,
  salaryRange: string,
  locationType: string,
  description: string,
  requirements: string[],
  benefits: string[],
): SystemTemplateSeed {
  return { title, department, employmentType, salaryRange, locationType, description, requirements, benefits };
}

const COMMON_REQ = [
  'Must be authorized to work in the United States',
  'Reliable and punctual',
  'Friendly and professional attitude',
];

const COMMON_BEN = [
  'Competitive pay',
  'Paid training',
  'Team-oriented environment',
  'Growth and advancement opportunities',
];

export const SYSTEM_TEMPLATES_BY_INDUSTRY: Record<
  Exclude<CompanyIndustry, 'CUSTOM'>,
  SystemTemplateSeed[]
> = {
  SHIPPING_RETAIL: [
    tpl(
      'Customer Service Associate',
      'Customer Service',
      'Part-Time',
      '$14 – $16/hr',
      'On-site',
      'Assist customers with inquiries, process transactions, and ensure every visitor has a positive in-store experience.',
      [...COMMON_REQ, 'Basic computer skills', 'Strong communication skills', 'Cash handling experience'],
      [...COMMON_BEN, 'Flexible scheduling', 'Employee discounts'],
    ),
    tpl(
      'Print & Shipping Associate',
      'Shipping & Print',
      'Full-Time',
      '$16 – $18/hr',
      'On-site',
      'Greet customers, process shipping and packing orders, handle printing and document services, and operate the POS system.',
      [...COMMON_REQ, 'Basic computer skills', 'Shipping and packing experience', 'Ability to lift up to 50 lbs'],
      [...COMMON_BEN, 'Flexible scheduling'],
    ),
    tpl(
      'Retail Sales Associate',
      'Sales',
      'Part-Time',
      '$14 – $16/hr',
      'In-store',
      'Help customers find products and services, upsell shipping and print solutions, and maintain a welcoming store environment.',
      [...COMMON_REQ, 'POS system experience', 'Customer service experience preferred', 'Flexible schedule including weekends'],
      [...COMMON_BEN, 'Employee discounts', 'Performance bonuses'],
    ),
    tpl(
      'Notary Associate',
      'Operations',
      'Part-Time',
      '$16 – $18/hr',
      'In-store',
      'Provide notary services while supporting general store operations including customer service, shipping, and printing.',
      [...COMMON_REQ, 'Notary commission (or willing to obtain)', 'Customer service experience preferred'],
      [...COMMON_BEN, 'Flexible scheduling'],
    ),
    tpl(
      'Shift Supervisor',
      'Management',
      'Full-Time',
      '$18 – $22/hr',
      'On-site',
      'Lead store operations during assigned shifts, coach associates, and ensure service standards are met.',
      [...COMMON_REQ, 'Leadership or supervisory experience', 'Flexible schedule including weekends'],
      [...COMMON_BEN, 'Performance bonuses', 'Career development programs'],
    ),
    tpl(
      'Assistant Manager',
      'Management',
      'Full-Time',
      '$45,000 – $55,000/year',
      'On-site',
      'Support the Store Manager with staffing, training, inventory, and customer service standards.',
      [...COMMON_REQ, 'Leadership or supervisory experience', 'Retail or franchise experience preferred'],
      [...COMMON_BEN, 'Health insurance (full-time)', 'Performance bonuses'],
    ),
    tpl(
      'Store Manager',
      'Management',
      'Full-Time',
      '$55,000 – $70,000/year',
      'On-site',
      'Lead full store operations including P&L performance, hiring, training, customer experience, and compliance.',
      [...COMMON_REQ, 'Leadership or supervisory experience', 'Inventory management experience'],
      [...COMMON_BEN, 'Health insurance (full-time)', 'Paid time off', '401(k) retirement plan'],
    ),
  ],
  NAIL_SALON: [
    tpl(
      'Nail Technician',
      'Service',
      'Full-Time',
      '$16 – $22/hr',
      'On-site',
      'Perform manicures, pedicures, gel applications, and nail art while maintaining sanitation standards.',
      [...COMMON_REQ, 'State nail technician license (or willing to obtain)', 'Ability to stand for extended periods'],
      [...COMMON_BEN, 'Tips (where applicable)', 'Flexible scheduling', 'Employee discounts'],
    ),
    tpl(
      'Pedicure Technician',
      'Service',
      'Full-Time',
      '$16 – $20/hr',
      'On-site',
      'Provide pedicure services, foot care treatments, and maintain a clean, relaxing station.',
      [...COMMON_REQ, 'State nail technician license (or willing to obtain)', 'Ability to stand for extended periods'],
      [...COMMON_BEN, 'Tips (where applicable)', 'Flexible scheduling'],
    ),
    tpl(
      'Receptionist',
      'Front Desk',
      'Part-Time',
      '$14 – $16/hr',
      'On-site',
      'Greet clients, schedule appointments, manage the front desk, and process payments.',
      [...COMMON_REQ, 'Basic computer skills', 'Cash handling experience', 'Strong communication skills'],
      [...COMMON_BEN, 'Flexible scheduling', 'Employee discounts'],
    ),
    tpl(
      'Salon Manager',
      'Management',
      'Full-Time',
      '$45,000 – $55,000/year',
      'On-site',
      'Oversee daily salon operations, staff scheduling, inventory, and client satisfaction.',
      [...COMMON_REQ, 'Leadership or supervisory experience', 'Salon or spa management experience preferred'],
      [...COMMON_BEN, 'Health insurance (full-time)', 'Performance bonuses'],
    ),
    tpl(
      'Lash Technician',
      'Service',
      'Full-Time',
      '$18 – $28/hr',
      'On-site',
      'Apply lash extensions, perform lash lifts, and consult with clients on aftercare.',
      [...COMMON_REQ, 'Lash certification (or willing to obtain)', 'Attention to detail'],
      [...COMMON_BEN, 'Tips (where applicable)', 'Paid training'],
    ),
    tpl(
      'Waxing Specialist',
      'Service',
      'Full-Time',
      '$16 – $22/hr',
      'On-site',
      'Perform waxing services, maintain sanitation standards, and educate clients on aftercare.',
      [...COMMON_REQ, 'Waxing certification (or willing to obtain)', 'Customer service experience preferred'],
      [...COMMON_BEN, 'Tips (where applicable)', 'Employee discounts'],
    ),
    tpl(
      'Spa Coordinator',
      'Front Desk',
      'Part-Time',
      '$14 – $16/hr',
      'On-site',
      'Coordinate spa appointments, manage client flow, and support front-of-house operations.',
      [...COMMON_REQ, 'Basic computer skills', 'Strong communication skills', 'Customer service experience preferred'],
      [...COMMON_BEN, 'Flexible scheduling', 'Employee discounts'],
    ),
  ],
  RESTAURANT: [
    tpl(
      'Server',
      'Front of House',
      'Part-Time',
      '$14 – $16/hr',
      'On-site',
      'Take orders, serve food and beverages, and provide attentive hospitality.',
      [...COMMON_REQ, 'Customer service experience preferred', 'Flexible schedule including weekends'],
      [...COMMON_BEN, 'Tips (where applicable)', 'Meal discounts'],
    ),
    tpl(
      'Cook',
      'Kitchen',
      'Full-Time',
      '$16 – $20/hr',
      'On-site',
      'Prepare menu items to spec, maintain kitchen cleanliness, and follow food safety standards.',
      [...COMMON_REQ, 'Food handler certification (or willing to obtain)', 'Kitchen experience preferred'],
      [...COMMON_BEN, 'Meal discounts', 'Paid training'],
    ),
    tpl(
      'Dishwasher',
      'Kitchen',
      'Part-Time',
      '$12 – $14/hr',
      'On-site',
      'Wash dishes and kitchen equipment and keep the dish area organized.',
      [...COMMON_REQ, 'Ability to stand for extended periods'],
      [...COMMON_BEN, 'Meal discounts', 'Flexible scheduling'],
    ),
    tpl(
      'Host',
      'Front of House',
      'Part-Time',
      '$12 – $14/hr',
      'On-site',
      'Greet guests, manage waitlists, and seat diners while keeping the front of house organized.',
      [...COMMON_REQ, 'Customer service experience preferred', 'Flexible schedule including weekends'],
      [...COMMON_BEN, 'Meal discounts', 'Flexible scheduling'],
    ),
    tpl(
      'Manager',
      'Management',
      'Full-Time',
      '$45,000 – $55,000/year',
      'On-site',
      'Lead restaurant operations including staffing, food quality, inventory, and guest experience.',
      [...COMMON_REQ, 'Leadership or supervisory experience', 'Food handler certification (or willing to obtain)'],
      [...COMMON_BEN, 'Health insurance (full-time)', 'Paid time off'],
    ),
  ],
  ROOFING: [
    tpl(
      'Roofing Laborer',
      'Field Operations',
      'Full-Time',
      '$16 – $22/hr',
      'On-site',
      'Install, repair, and maintain roofing systems on residential and commercial properties.',
      [...COMMON_REQ, 'Ability to lift up to 50 lbs', 'Comfort working at heights', 'OSHA safety training preferred'],
      [...COMMON_BEN, 'Overtime opportunities', 'Paid training'],
    ),
    tpl(
      'Sales Representative',
      'Sales',
      'Full-Time',
      'Competitive — DOE',
      'Hybrid',
      'Conduct in-home inspections, prepare estimates, and close roofing contracts.',
      [...COMMON_REQ, 'Valid driver\'s license', 'Sales experience preferred', 'Strong communication skills'],
      [...COMMON_BEN, 'Performance bonuses', 'Company vehicle or mileage reimbursement'],
    ),
    tpl(
      'Project Manager',
      'Management',
      'Full-Time',
      '$55,000 – $70,000/year',
      'Hybrid',
      'Coordinate roofing projects from estimate through completion and manage crews and materials.',
      [...COMMON_REQ, 'Leadership or supervisory experience', 'Roofing or construction experience preferred', 'Valid driver\'s license'],
      [...COMMON_BEN, 'Health insurance (full-time)', 'Performance bonuses'],
    ),
    tpl(
      'Estimator',
      'Sales',
      'Full-Time',
      '$45,000 – $55,000/year',
      'Hybrid',
      'Inspect properties, measure roofs, and prepare detailed estimates for the sales team.',
      [...COMMON_REQ, 'Roofing or construction estimating experience preferred', 'Valid driver\'s license'],
      [...COMMON_BEN, 'Performance bonuses', 'Paid training'],
    ),
    tpl(
      'Office Assistant',
      'Administration',
      'Full-Time',
      '$16 – $20/hr',
      'On-site',
      'Support office operations including scheduling, customer calls, filing, and data entry.',
      [...COMMON_REQ, 'Basic computer skills', 'Strong communication skills', 'Organizational skills'],
      [...COMMON_BEN, 'Health insurance (full-time)', 'Paid training'],
    ),
  ],
  FACTORY: [
    tpl(
      'Production Worker',
      'Production',
      'Full-Time',
      '$16 – $18/hr',
      'On-site',
      'Operate production equipment, meet daily output targets, and follow safety and quality procedures on the manufacturing floor.',
      [...COMMON_REQ, 'Ability to stand for extended periods', 'Ability to lift up to 50 lbs', 'OSHA safety training preferred'],
      [...COMMON_BEN, 'Overtime opportunities', 'Health insurance (full-time)', 'Paid training'],
    ),
    tpl(
      'Assembly Technician',
      'Production',
      'Full-Time',
      '$16 – $20/hr',
      'On-site',
      'Assemble components to specification, perform in-process quality checks, and document production output.',
      [...COMMON_REQ, 'Manufacturing or assembly experience preferred', 'Attention to detail', 'Ability to lift up to 50 lbs'],
      [...COMMON_BEN, 'Paid training', 'Cross-training opportunities', 'Stable work environment'],
    ),
    tpl(
      'QA/QC Inspector',
      'Production',
      'Full-Time',
      '$18 – $22/hr',
      'On-site',
      'Inspect finished goods, document defects, and ensure products meet quality standards before shipment.',
      [...COMMON_REQ, 'Quality control experience preferred', 'Attention to detail', 'Basic computer skills'],
      [...COMMON_BEN, 'Health insurance (full-time)', 'Career development programs'],
    ),
    tpl(
      'Shipping & Receiving',
      'Fulfillment',
      'Full-Time',
      '$16 – $18/hr',
      'On-site',
      'Receive inbound materials, pick and pack orders, and prepare outbound shipments with accurate documentation.',
      [...COMMON_REQ, 'Forklift certification preferred', 'Ability to lift up to 50 lbs', 'Inventory management experience'],
      [...COMMON_BEN, 'Overtime opportunities', 'Paid training'],
    ),
    tpl(
      'Supervisor',
      'Management',
      'Full-Time',
      '$22 – $28/hr',
      'On-site',
      'Supervise production teams, enforce safety protocols, track KPIs, and coordinate shift schedules.',
      [...COMMON_REQ, 'Leadership or supervisory experience', 'Manufacturing experience preferred', 'OSHA safety training preferred'],
      [...COMMON_BEN, 'Health insurance (full-time)', 'Performance bonuses', '401(k) retirement plan'],
    ),
  ],
  RETAIL: [
    tpl(
      'Retail Sales Associate',
      'Sales',
      'Part-Time',
      '$14 – $16/hr',
      'In-store',
      'Assist customers on the sales floor, maintain product displays, and support daily store operations.',
      [...COMMON_REQ, 'Customer service experience preferred', 'Flexible schedule including weekends', 'Cash handling experience'],
      [...COMMON_BEN, 'Employee discounts', 'Flexible scheduling'],
    ),
    tpl(
      'Cashier',
      'Sales',
      'Part-Time',
      '$12 – $14/hr',
      'In-store',
      'Process customer transactions accurately, handle returns, and provide friendly checkout service.',
      [...COMMON_REQ, 'Cash handling experience', 'POS system experience', 'Friendly and professional attitude'],
      [...COMMON_BEN, 'Flexible scheduling', 'Employee discounts'],
    ),
    tpl(
      'Stock Associate',
      'Operations',
      'Part-Time',
      '$14 – $16/hr',
      'On-site',
      'Receive and unpack inventory, restock shelves, and maintain organized backroom and sales floor areas.',
      [...COMMON_REQ, 'Ability to lift up to 50 lbs', 'Ability to stand for extended periods'],
      [...COMMON_BEN, 'Flexible scheduling', 'Employee discounts'],
    ),
    tpl(
      'Assistant Manager',
      'Management',
      'Full-Time',
      '$35,000 – $45,000/year',
      'On-site',
      'Support the store manager with staffing, training, inventory, and customer service standards.',
      [...COMMON_REQ, 'Leadership or supervisory experience', 'Retail experience preferred', 'Strong communication skills'],
      [...COMMON_BEN, 'Health insurance (full-time)', 'Performance bonuses', 'Career development programs'],
    ),
    tpl(
      'Store Manager',
      'Management',
      'Full-Time',
      '$45,000 – $55,000/year',
      'On-site',
      'Lead all store operations including sales goals, hiring, merchandising, and customer experience.',
      [...COMMON_REQ, 'Leadership or supervisory experience', 'Retail management experience preferred', 'Inventory management experience'],
      [...COMMON_BEN, 'Health insurance (full-time)', 'Paid time off', '401(k) retirement plan'],
    ),
  ],
  MEDICAL_OFFICE: [
    tpl(
      'Medical Assistant',
      'Clinical',
      'Full-Time',
      '$16 – $22/hr',
      'On-site',
      'Room patients, take vitals, assist providers with procedures, and maintain clinical supplies.',
      [...COMMON_REQ, 'Medical assistant certification (or willing to obtain)', 'HIPAA awareness preferred'],
      [...COMMON_BEN, 'Health insurance (full-time)', 'Paid training'],
    ),
    tpl(
      'Receptionist',
      'Front Desk',
      'Full-Time',
      '$14 – $18/hr',
      'On-site',
      'Greet patients, schedule appointments, verify insurance, and manage front office workflow.',
      [...COMMON_REQ, 'Basic computer skills', 'Strong communication skills', 'HIPAA awareness preferred'],
      [...COMMON_BEN, 'Health insurance (full-time)', 'Paid time off'],
    ),
    tpl(
      'Nurse',
      'Clinical',
      'Full-Time',
      '$22 – $28/hr',
      'On-site',
      'Provide clinical nursing support, patient education, and assist physicians with procedures.',
      [...COMMON_REQ, 'RN or LPN license (or willing to obtain)', 'HIPAA awareness preferred', 'Professional bedside manner'],
      [...COMMON_BEN, 'Health insurance (full-time)', 'Paid time off', '401(k) retirement plan'],
    ),
  ],
};

/** @deprecated use SYSTEM_TEMPLATES_BY_INDUSTRY */
export const JOB_TEMPLATES_SEED = SYSTEM_TEMPLATES_BY_INDUSTRY.SHIPPING_RETAIL;
