export const LOOKUP_SEED = {
  department: [
    'Operations',
    'Customer Service',
    'Shipping & Print',
    'Sales',
    'Management',
    'Administration',
    'Fulfillment',
  ],
  job_title: [
    'Print & Shipping Associate',
    'Customer Service Associate',
    'Retail Sales Associate',
    'Shift Supervisor',
    'Assistant Manager',
    'Store Manager',
    'Notary Associate',
    'Part-Time Associate',
    'Full-Time Associate',
    'Center Associate',
  ],
  employment_type: [
    'Full-Time',
    'Part-Time',
    'Seasonal',
    'Contract',
    'Temporary',
    'Either',
  ],
  salary_range: [
    '$12 – $14/hr',
    '$14 – $16/hr',
    '$16 – $18/hr',
    '$18 – $22/hr',
    '$22 – $28/hr',
    '$28 – $35/hr',
    '$35,000 – $45,000/year',
    '$45,000 – $55,000/year',
    '$55,000 – $70,000/year',
    'Competitive — DOE',
  ],
  location: [
    'On-site',
    'In-store',
    'Store Location',
    'Hybrid',
  ],
  requirement: [
    'Friendly and professional attitude',
    'Reliable and punctual',
    'Basic computer skills',
    'Customer service experience preferred',
    'Must be authorized to work in the United States',
    'Ability to stand for extended periods',
    'Ability to lift up to 50 lbs',
    'Cash handling experience',
    'POS system experience',
    'Shipping and packing experience',
    'Printing and document services experience',
    'Retail or franchise experience preferred',
    'Strong communication skills',
    'Team-oriented mindset',
    'Flexible schedule including weekends',
    'High school diploma or equivalent',
    'Notary commission (or willing to obtain)',
    'Leadership or supervisory experience',
    'Inventory management experience',
    'Problem-solving skills',
  ],
  benefit: [
    'Flexible scheduling',
    'Team-oriented environment',
    'Growth and advancement opportunities',
    'Employee discounts',
    'Paid training',
    'Competitive pay',
    'Health insurance (full-time)',
    'Paid time off',
    '401(k) retirement plan',
    'Holiday pay',
    'Performance bonuses',
    'Career development programs',
    'Supportive management',
    'Stable work environment',
    'Cross-training opportunities',
  ],
} as const;

export type LookupCategory = keyof typeof LOOKUP_SEED;

export const JOB_TEMPLATES_SEED = [
  {
    name: 'Print & Shipping Associate',
    title: 'Print & Shipping Associate',
    department: 'Shipping & Print',
    employmentType: 'Full-Time',
    salary: '$16 – $18/hr',
    location: 'On-site',
    description: `Join our team as a Print & Shipping Associate at The UPS Store. In this role you will greet customers, process shipping and packing orders, handle printing and document services, and operate the POS system while maintaining a clean, organized store environment.

This is a great opportunity for someone who enjoys helping customers and thrives in a fast-paced retail setting.`,
    requirements: [
      'Friendly and professional attitude',
      'Reliable and punctual',
      'Basic computer skills',
      'Customer service experience preferred',
      'Must be authorized to work in the United States',
      'Ability to lift up to 50 lbs',
      'Shipping and packing experience',
    ].join('\n'),
    benefits: [
      'Flexible scheduling',
      'Team-oriented environment',
      'Growth and advancement opportunities',
      'Paid training',
      'Competitive pay',
    ].join('\n'),
  },
  {
    name: 'Customer Service Associate',
    title: 'Customer Service Associate',
    department: 'Customer Service',
    employmentType: 'Part-Time',
    salary: '$14 – $16/hr',
    location: 'On-site',
    description: `We are looking for a friendly, dependable Customer Service Associate to be the face of our store. You will assist customers with inquiries, process transactions, and ensure every visitor has a positive experience.

Ideal candidates are outgoing, patient, and committed to delivering excellent service.`,
    requirements: [
      'Friendly and professional attitude',
      'Reliable and punctual',
      'Basic computer skills',
      'Customer service experience preferred',
      'Must be authorized to work in the United States',
      'Strong communication skills',
      'Cash handling experience',
    ].join('\n'),
    benefits: [
      'Flexible scheduling',
      'Team-oriented environment',
      'Employee discounts',
      'Paid training',
      'Supportive management',
    ].join('\n'),
  },
  {
    name: 'Retail Sales Associate',
    title: 'Retail Sales Associate',
    department: 'Sales',
    employmentType: 'Part-Time',
    salary: '$14 – $16/hr',
    location: 'In-store',
    description: `As a Retail Sales Associate, you will help customers find the right products and services, upsell shipping and print solutions, and contribute to store revenue goals.

You will work closely with the team to create a welcoming environment and drive customer satisfaction.`,
    requirements: [
      'Friendly and professional attitude',
      'Retail or franchise experience preferred',
      'POS system experience',
      'Strong communication skills',
      'Must be authorized to work in the United States',
      'Flexible schedule including weekends',
    ].join('\n'),
    benefits: [
      'Flexible scheduling',
      'Performance bonuses',
      'Team-oriented environment',
      'Cross-training opportunities',
      'Competitive pay',
    ].join('\n'),
  },
  {
    name: 'Shift Supervisor',
    title: 'Shift Supervisor',
    department: 'Management',
    employmentType: 'Full-Time',
    salary: '$18 – $22/hr',
    location: 'On-site',
    description: `The Shift Supervisor leads store operations during assigned shifts, coaches associates, ensures service standards are met, and assists the manager with daily workflow and customer escalations.

This role is ideal for experienced retail professionals ready to take on leadership responsibility.`,
    requirements: [
      'Leadership or supervisory experience',
      'Customer service experience preferred',
      'Reliable and punctual',
      'POS system experience',
      'Problem-solving skills',
      'Must be authorized to work in the United States',
      'Flexible schedule including weekends',
    ].join('\n'),
    benefits: [
      'Growth and advancement opportunities',
      'Paid training',
      'Competitive pay',
      'Performance bonuses',
      'Career development programs',
    ].join('\n'),
  },
  {
    name: 'Assistant Manager',
    title: 'Assistant Manager',
    department: 'Management',
    employmentType: 'Full-Time',
    salary: '$45,000 – $55,000/year',
    location: 'On-site',
    description: `The Assistant Manager supports the Store Manager in all aspects of store operations including staffing, training, customer service, inventory, and financial performance.

You will help build a high-performing team and ensure the store meets brand standards and business goals.`,
    requirements: [
      'Leadership or supervisory experience',
      'Retail or franchise experience preferred',
      'Inventory management experience',
      'Strong communication skills',
      'Problem-solving skills',
      'High school diploma or equivalent',
      'Must be authorized to work in the United States',
    ].join('\n'),
    benefits: [
      'Health insurance (full-time)',
      'Paid time off',
      '401(k) retirement plan',
      'Performance bonuses',
      'Career development programs',
      'Growth and advancement opportunities',
    ].join('\n'),
  },
  {
    name: 'Store Manager',
    title: 'Store Manager',
    department: 'Management',
    employmentType: 'Full-Time',
    salary: '$55,000 – $70,000/year',
    location: 'On-site',
    description: `The Store Manager is responsible for the full operation of the franchise location — P&L performance, hiring, training, customer experience, compliance, and community engagement.

We are seeking an experienced leader with a passion for retail and team development.`,
    requirements: [
      'Leadership or supervisory experience',
      'Retail or franchise experience preferred',
      'Inventory management experience',
      'Strong communication skills',
      'Problem-solving skills',
      'High school diploma or equivalent',
      'Must be authorized to work in the United States',
    ].join('\n'),
    benefits: [
      'Health insurance (full-time)',
      'Paid time off',
      '401(k) retirement plan',
      'Performance bonuses',
      'Career development programs',
      'Competitive pay',
    ].join('\n'),
  },
  {
    name: 'Notary Associate',
    title: 'Notary Associate',
    department: 'Operations',
    employmentType: 'Part-Time',
    salary: '$16 – $18/hr',
    location: 'In-store',
    description: `The Notary Associate provides notary services to customers while also supporting general store operations including customer service, shipping, and printing.

You will ensure all notarizations comply with state requirements and deliver a professional, trustworthy experience.`,
    requirements: [
      'Notary commission (or willing to obtain)',
      'Friendly and professional attitude',
      'Customer service experience preferred',
      'Basic computer skills',
      'Must be authorized to work in the United States',
      'Reliable and punctual',
      'Strong communication skills',
    ].join('\n'),
    benefits: [
      'Flexible scheduling',
      'Paid training',
      'Team-oriented environment',
      'Competitive pay',
      'Supportive management',
    ].join('\n'),
  },
];
